[build]
rustflags = [
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Wclippy::cargo",
    "-Wclippy::complexity",
    "-Wclippy::perf",
    "-Wclippy::style",
    "-Wclippy::correctness",
    "-Wclippy::suspicious",
    # Allow some lints that are too restrictive
    "-Aclippy::module_name_repetitions",
    "-Aclippy::too_many_lines",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
    "-Aclippy::must_use_candidate",
]
